
# "Mathematics is the art of giving the same name to different things.
# Poetry is the art of giving different names to the same thing"
# ~ Henri Poincaré

## # If you want to exist in the parallel universe,
## # you just add "_from_parallel_universe" at the ending of the variable
## # NAME, SRC, and BUILD.
## NAME = push_swap_from_parallel_universe
## SRC = src_from_parallel_universe
## BUILD = build_from_parallel_universe

NAME = push_swap
SRC = src
BUILD = build
LIB = appendix.h
